language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
# command to install dependencies
before_install:
    - sudo apt-get -qq update
    - sudo apt-get install gfortran -y
install:
    - pip install .[lint,test]
# command to run tests
script:
    - python setup.py lint
    - python setup.py test
